window.BIRTHDAYS = [
//BanGDream角色
  { name: "牛込里美", birthday: "03-23", dept: "BanGDream·Poppin'Party" },
  { name: "山吹沙绫", birthday: "05-19", dept: "BanGDream·Poppin'Party" },
  { name: "户山香澄", birthday: "07-14", dept: "BanGDream·Poppin'Party" },
  { name: "市谷有咲", birthday: "10-27", dept: "BanGDream·Poppin'Party" },
  { name: "花园多惠", birthday: "12-04", dept: "BanGDream·Poppin'Party" },

  { name: "爱美", birthday: "1991-12-25", dept: "声优-户山香澄" },
  { name: "大桥彩香", birthday: "1994-09-13", dept: "声优-山吹沙绫" },
  { name: "西本里美", birthday: "1994-10-25", dept: "声优-牛込里美" },
  { name: "大冢纱英", birthday: "1995-10-10", dept: "声优-花园多惠" },

  { name: "羽泽鸫", birthday: "01-07", dept: "BanGDream·Afterglow" },
  { name: "美竹兰", birthday: "04-10", dept: "BanGDream·Afterglow" },
  { name: "宇田川巴", birthday: "04-15", dept: "BanGDream·Afterglow" },
  { name: "青叶摩卡", birthday: "09-03", dept: "BanGDream·Afterglow" },
  { name: "上原绯玛丽", birthday: "10-23", dept: "BanGDream·Afterglow" },

  { name: "加藤英美里", birthday: "1983-11-26", dept: "声优-上原绯玛丽" },
  { name: "金元寿子", birthday: "1987-12-16", dept: "声优-羽泽鸫" },
  { name: "三泽纱千香", birthday: "1993-01-13", dept: "声优-青叶摩卡" },
  { name: "佐仓绫音", birthday: "1994-01-29", dept: "声优-美竹兰" },

  { name: "冰川日菜", birthday: "03-20", dept: "BanGDream·Pastel*Palettes" },
  { name: "白鹭千圣", birthday: "04-06", dept: "BanGDream·Pastel*Palettes" },
  { name: "若宫伊芙", birthday: "06-27", dept: "BanGDream·Pastel*Palettes" },
  { name: "大和麻弥", birthday: "11-03", dept: "BanGDream·Pastel*Palettes" },
  { name: "丸山彩", birthday: "12-27", dept: "BanGDream·Pastel*Palettes" },

  { name: "中上育实", birthday: "1983-06-18", dept: "声优-大和麻弥" },
  { name: "秦佐和子", birthday: "1988-09-14", dept: "声优-若宫伊芙" },
  { name: "上坂堇", birthday: "1991-12-19", dept: "声优-白鹭千圣" },
  { name: "小泽亚李", birthday: "1992-08-10", dept: "声优-冰川日菜" },
  { name: "前岛亚美", birthday: "1997-11-22", dept: "声优-丸山彩" },

  { name: "冰川纱夜", birthday: "03-20", dept: "BanGDream·Roselia" },
  { name: "宇田川亚子", birthday: "07-03", dept: "BanGDream·Roselia" },
  { name: "今井莉莎", birthday: "08-25", dept: "BanGDream·Roselia" },
  { name: "白金燐子", birthday: "10-17", dept: "BanGDream·Roselia" },
  { name: "凑友希那", birthday: "10-26", dept: "BanGDream·Roselia" },

  { name: "樱川惠", birthday: "1988-10-24", dept: "声优-宇田川亚子" },
  { name: "工藤晴香", birthday: "1989-03-16", dept: "声优-冰川纱夜" },
  { name: "志崎桦音", birthday: "1995-02-08", dept: "声优-白金燐子" },
  { name: "中岛由贵", birthday: "1997-09-12", dept: "声优-今井莉莎、日野森志步" },

  { name: "濑田薰", birthday: "02-28", dept: "BanGDream·Hello Happy World!" },
  { name: "松原花音", birthday: "05-11", dept: "BanGDream·Hello Happy World!" },
  { name: "北泽育美", birthday: "07-30", dept: "BanGDream·Hello Happy World!" },
  { name: "弦卷心", birthday: "08-08", dept: "BanGDream·Hello Happy World!" },
  { name: "奥泽美咲", birthday: "10-01", dept: "BanGDream·Hello Happy World!" },

  { name: "田所梓", birthday: "1993-11-10", dept: "声优-濑田薰" },
  { name: "吉田有里", birthday: "1992-08-18", dept: "声优-北泽育美" },
  { name: "丰田萌绘", birthday: "1995-03-15", dept: "声优-松原花音" },
  { name: "黑泽朋世", birthday: "1996-04-10", dept: "声优-奥泽美咲" },
  { name: "伊藤美来", birthday: "1996-10-12", dept: "声优-弦卷心" },

  { name: "仓田真白", birthday: "02-19", dept: "BanGDream·Morfonica" },
  { name: "广町七深", birthday: "06-16", dept: "BanGDream·Morfonica" },
  { name: "二叶筑紫", birthday: "09-15", dept: "BanGDream·Morfonica" },
  { name: "八潮瑠唯", birthday: "11-19", dept: "BanGDream·Morfonica" },
  { name: "桐谷透子", birthday: "12-16", dept: "BanGDream·Morfonica" },

  { name: "mika", birthday: "06-24", dept: "声优-二叶筑紫" },
  { name: "Ayasa", birthday: "1991-10-19", dept: "声优-八潮瑠唯" },
  { name: "西尾夕香", birthday: "1994-03-31", dept: "声优-广町七深" },
  { name: "直田姬奈", birthday: "1995-04-17", dept: "声优-桐谷透子" },
  { name: "进藤天音", birthday: "2004-04-20", dept: "声优-仓田真白、桂城泉" },

  { name: "Layer", birthday: "01-13", dept: "BanGDream·RAISE A SUILEN" },
  { name: "Pareo", birthday: "03-25", dept: "BanGDream·RAISE A SUILEN" },
  { name: "Masking", birthday: "05-12", dept: "BanGDream·RAISE A SUILEN" },
  { name: "Lock", birthday: "07-17", dept: "BanGDream·RAISE A SUILEN" },
  { name: "Chuchu", birthday: "12-07", dept: "BanGDream·RAISE A SUILEN" },

  { name: "Raychell", birthday: "1985-01-13", dept: "声优-Layer" },
  { name: "夏芽", birthday: "1986-07-20", dept: "声优-Masking" },
  { name: "小原莉子", birthday: "1990-02-03", dept: "声优-Lock" },
  { name: "纺木吏佐", birthday: "1996-07-05", dept: "声优-Chuchu" },
  { name: "仓知玲凤", birthday: "1997-05-22", dept: "声优-Pareo" },

  { name: "要乐奈", birthday: "02-22", dept: "BanGDream·MyGO!!!!!" },
  { name: "长崎素世", birthday: "05-27", dept: "BanGDream·MyGO!!!!!" },
  { name: "椎名立希", birthday: "08-09", dept: "BanGDream·MyGO!!!!!" },
  { name: "千早爱音", birthday: "09-08", dept: "BanGDream·MyGO!!!!!" },
  { name: "高松灯", birthday: "11-22", dept: "BanGDream·MyGO!!!!!" },

  { name: "小日向美香", birthday: "2000-03-14", dept: "声优-长崎素世" },
  { name: "羊宫妃那", birthday: "2000-03-26", dept: "声优-高松灯" },
  { name: "青木阳菜", birthday: "2000-01-05", dept: "声优-要乐奈" },
  { name: "立石凛", birthday: "2001-07-10", dept: "声优-千早爱音" },
  { name: "林鼓子", birthday: "2000-05-15", dept: "声优-椎名立希、优木雪菜" },

  { name: "若叶睦", birthday: "01-14", dept: "BanGDream·Ave Mujica" },
  { name: "八幡海铃", birthday: "04-07", dept: "BanGDream·Ave Mujica" },
  { name: "祐天寺喵梦", birthday: "06-01", dept: "BanGDream·Ave Mujica" },
  { name: "三角初华", birthday: "06-26", dept: "BanGDream·Ave Mujica" },
  { name: "丰川祥子", birthday: "02-14", dept: "BanGDream·Ave Mujica" },

  { name: "冈田梦以", birthday: "1996-05-19", dept: "声优-八幡海铃" },
  { name: "佐佐木李子", birthday: "1997-11-10", dept: "声优-三角初华" },
  { name: "米泽茜", birthday: "1998-12-31", dept: "声优-祐天寺喵梦" },
  { name: "高尾奏音", birthday: "2002-09-10", dept: "声优-丰川祥子" },
  { name: "渡濑结月", birthday: "2003-02-18", dept: "声优-若叶睦" },

  { name: "峰月律", birthday: "02-07", dept: "BanGDream·夢限大みゅーたいぷ" },
  { name: "宫永野乃花", birthday: "04-17", dept: "BanGDream·夢限大みゅーたいぷ" },
  { name: "仲町阿拉蕾", birthday: "08-16", dept: "BanGDream·夢限大みゅーたいぷ" },
  { name: "藤都子", birthday: "09-19", dept: "BanGDream·夢限大みゅーたいぷ" },
  { name: "千石由乃", birthday: "11-04", dept: "BanGDream·夢限大みゅーたいぷ" },

  { name: "汐见萤", birthday: "03-12", dept: "BanGDream·millsage" },
  { name: "伊泽枣", birthday: "03-30", dept: "BanGDream·millsage" },
  { name: "滨崎茉幌", birthday: "07-16", dept: "BanGDream·millsage" },
  { name: "和泉朋花", birthday: "10-24", dept: "BanGDream·millsage" },
  { name: "琴平凪", birthday: "12-10", dept: "BanGDream·millsage" },

  { name: "结川麻希", birthday: "02-15", dept: "声优-琴平凪" },
  { name: "伊驹百合绘", birthday: "02-24", dept: "声优-滨崎茉幌" },
  { name: "千春", birthday: "1995-04-10", dept: "声优-伊泽枣" },
  { name: "药师寺李有", birthday: "09-11", dept: "声优-汐见萤" },
  { name: "咲川雏乃", birthday: "2001-01-22", dept: "声优-和泉朋花" },
  
  { name: "四宫宁月", birthday: "03-05", dept: "BanGDream·一家Dumb Rock!" },
  { name: "梅里千樱梨", birthday: "04-02", dept: "BanGDream·一家Dumb Rock!" },
  { name: "矢仓蓬咲", birthday: "05-06", dept: "BanGDream·一家Dumb Rock!" },
  { name: "须贺蕾叶", birthday: "07-28", dept: "BanGDream·一家Dumb Rock!" },
  { name: "马桥心玖", birthday: "10-04", dept: "BanGDream·一家Dumb Rock!" },

  { name: "远野光", birthday: "1996-03-05", dept: "声优-四宫宁月" },
  { name: "菱川花菜", birthday: "2003-05-19", dept: "声优-梅里千樱梨" },
  { name: "凉泉樱花", birthday: "2004-03-05", dept: "声优-马桥心玖" },
  { name: "橘芽衣", birthday: "2008-11-19", dept: "声优-须贺蕾叶" },
//LoveLive!角色
  { name: "小泉花阳", birthday: "01-17", dept: "LoveLive!·μ's" },
  { name: "园田海未", birthday: "03-15", dept: "LoveLive!·μ's" },
  { name: "西木野真姬", birthday: "04-19", dept: "LoveLive!·μ's" },
  { name: "东条希", birthday: "06-09", dept: "LoveLive!·μ's" },
  { name: "矢泽妮可", birthday: "07-22", dept: "LoveLive!·μ's" },
  { name: "高坂穗乃果", birthday: "08-03", dept: "LoveLive!·μ's" },
  { name: "南小鸟", birthday: "09-12", dept: "LoveLive!·μ's" },
  { name: "绚濑绘里", birthday: "10-21", dept: "LoveLive!·μ's" },
  { name: "星空凛", birthday: "11-01", dept: "LoveLive!·μ's" },

  { name: "南条爱乃", birthday: "1984-07-12", dept: "声优-绚濑绘里" },
  { name: "新田惠海", birthday: "1985-12-10", dept: "声优-高坂穗乃果" },
  { name: "内田彩", birthday: "1986-07-23", dept: "声优-南小鸟" },
  { name: "Pile", birthday: "1988-05-02", dept: "声优-西木野真姬" },
  { name: "楠田亚衣奈", birthday: "1989-02-01", dept: "声优-东条希" },
  { name: "久保百合花", birthday: "1989-05-19", dept: "声优-小泉花阳" },
  { name: "徳井青空", birthday: "1984-12-26", dept: "声优-矢泽妮可" },
  { name: "饭田里穂", birthday: "1991-10-26", dept: "声优-星空凛" },

  { name: "黑泽黛雅", birthday: "01-01", dept: "LoveLive!·Aqours" },
  { name: "松浦果南", birthday: "02-10", dept: "LoveLive!·Aqours" },
  { name: "国木田花丸", birthday: "03-04", dept: "LoveLive!·Aqours" },
  { name: "渡边曜", birthday: "04-17", dept: "LoveLive!·Aqours" },
  { name: "小原鞠莉", birthday: "06-13", dept: "LoveLive!·Aqours" },
  { name: "津岛善子", birthday: "07-13", dept: "LoveLive!·Aqours" },
  { name: "高海千歌", birthday: "08-01", dept: "LoveLive!·Aqours" },
  { name: "樱内梨子", birthday: "09-19", dept: "LoveLive!·Aqours" },
  { name: "黑泽露比", birthday: "09-21", dept: "LoveLive!·Aqours" },

  { name: "逢田梨香子", birthday: "1992-08-08", dept: "声优-樱内梨子" },
  { name: "高槻加奈子", birthday: "1993-09-25", dept: "声优-国木田花丸" },
  { name: "小林爱香", birthday: "1993-10-23", dept: "声优-津岛善子" },
  { name: "小宫有纱", birthday: "1994-02-05", dept: "声优-黑泽黛雅" },
  { name: "诹访奈奈香", birthday: "1994-11-02", dept: "声优-松浦果南" },
  { name: "降幡愛", birthday: "1994-02-19", dept: "声优-黑泽露比、桃井爱莉" },
  { name: "铃木爱奈", birthday: "1995-07-23", dept: "声优-小原鞠莉" },
  { name: "伊波杏树", birthday: "1996-02-07", dept: "声优-高海千歌" },
  { name: "齐藤朱夏", birthday: "1996-08-16", dept: "声优-渡边曜" },

  { name: "中须霞", birthday: "01-23", dept: "LoveLive!·虹ヶ咲学園スクールアイドル同好会" },
  { name: "艾玛·维尔德", birthday: "01-23", dept: "LoveLive!·虹ヶ咲学園スクールアイドル同好会" },
  { name: "钟岚珠", birthday: "01-23", dept: "LoveLive!·虹ヶ咲学園スクールアイドル同好会" },
  { name: "上原步梦", birthday: "03-01", dept: "LoveLive!·虹ヶ咲学園スクールアイドル同好会" },
  { name: "樱坂雫", birthday: "04-03", dept: "LoveLive!·虹ヶ咲学園スクールアイドル同好会" },
  { name: "宫下爱", birthday: "05-30", dept: "LoveLive!·虹ヶ咲学園スクールアイドル同好会" },
  { name: "朝香果林", birthday: "06-29", dept: "LoveLive!·虹ヶ咲学園スクールアイドル同好会" },
  { name: "优木雪菜", birthday: "08-08", dept: "LoveLive!·虹ヶ咲学園スクールアイドル同好会" },
  { name: "三船栞子", birthday: "10-05", dept: "LoveLive!·虹ヶ咲学園スクールアイドル同好会" },
  { name: "天王寺璃奈", birthday: "11-13", dept: "LoveLive!·虹ヶ咲学園スクールアイドル同好会" },
  { name: "米娅·泰勒", birthday: "12-06", dept: "LoveLive!·虹ヶ咲学園スクールアイドル同好会" },
  { name: "近江彼方", birthday: "12-16", dept: "LoveLive!·虹ヶ咲学園スクールアイドル同好会" },

  { name: "田中千惠美", birthday: "1994-10-06", dept: "声优-天王寺璃奈" },
  { name: "鬼头明里", birthday: "1994-10-16", dept: "声优-近江彼方" },
  { name: "久保田未梦", birthday: "1995-01-31", dept: "声优-朝香果林" },
  { name: "相良茉优", birthday: "1995-04-17", dept: "声优-中须霞" },
  { name: "村上奈津实", birthday: "1995-09-07", dept: "声优-宫下爱" },
  { name: "前田佳织里", birthday: "1996-04-25", dept: "声优-樱坂雫" },
  { name: "内田秀", birthday: "1996-05-24", dept: "声优-米娅·泰勒" },
  { name: "法元明菜", birthday: "1996-08-05", dept: "声优-钟岚珠" },
  { name: "大西亚玖璃", birthday: "1997-05-02", dept: "声优-上原步梦" },
  { name: "指出毬亚", birthday: "1998-09-20", dept: "声优-艾玛·维尔德" },
  { name: "楠木灯", birthday: "1999-12-22", dept: "声优-优木雪菜（曾任）、宵崎奏" },

  { name: "薇恩·玛格丽特", birthday: "01-20", dept: "LoveLive!·Liella!" },
  { name: "岚千砂都", birthday: "02-25", dept: "LoveLive!·Liella!" },
  { name: "樱小路希奈子", birthday: "04-10", dept: "LoveLive!·Liella!" },
  { name: "涩谷香音", birthday: "05-01", dept: "LoveLive!·Liella!" },
  { name: "若菜四季", birthday: "06-17", dept: "LoveLive!·Liella!" },
  { name: "唐可可", birthday: "07-17", dept: "LoveLive!·Liella!" },
  { name: "鬼冢夏美", birthday: "08-07", dept: "LoveLive!·Liella!" },
  { name: "平安名堇", birthday: "09-28", dept: "LoveLive!·Liella!" },
  { name: "米女芽衣", birthday: "10-29", dept: "LoveLive!·Liella!" },
  { name: "叶月恋", birthday: "11-24", dept: "LoveLive!·Liella!" },
  { name: "鬼冢冬毬", birthday: "12-28", dept: "LoveLive!·Liella!" },

  { name: "Liyuu", birthday: "1997-01-09", dept: "声优-唐可可" },
  { name: "青山渚", birthday: "1998-05-16", dept: "声优-叶月恋" },
  { name: "岬奈子", birthday: "1999-03-08", dept: "声优-岚千砂都" },
  { name: "大熊和奏", birthday: "2001-04-13", dept: "声优-若菜四季" },
  { name: "薮岛朱音", birthday: "2001-07-18", dept: "声优-米女芽衣" },
  { name: "结那", birthday: "2001-09-27", dept: "声优-薇恩·玛格丽特" },
  { name: "伊达小百合", birthday: "2002-09-30", dept: "声优-涩谷香音" },
  { name: "铃原希实", birthday: "2002-11-01", dept: "声优-樱小路希奈子" },
  { name: "尚未Payton", birthday: "2003-07-01", dept: "声优-平安名堇" },
  { name: "绘森彩", birthday: "2004-02-23", dept: "声优-鬼塚夏美" },
  { name: "坂仓花", birthday: "2004-04-03", dept: "声优-鬼冢冬毬" },

  { name: "村野沙耶香", birthday: "01-13", dept: "LoveLive!·蓮ノ空女学院スクールアイドルクラブ" },
  { name: "徒町小铃", birthday: "02-28", dept: "LoveLive!·蓮ノ空女学院スクールアイドルクラブ" },
  { name: "日野下花帆", birthday: "05-22", dept: "LoveLive!·蓮ノ空女学院スクールアイドルクラブ" },
  { name: "乙宗梢", birthday: "06-15", dept: "LoveLive!·蓮ノ空女学院スクールアイドルクラブ" },
  { name: "塞拉斯·柳田·利林费尔德", birthday: "06-16", dept: "LoveLive!·蓮ノ空女学院スクールアイドルクラブ" },
  { name: "大泽瑠璃乃", birthday: "08-31", dept: "LoveLive!·蓮ノ空女学院スクールアイドルクラブ" },
  { name: "安养寺姬芽", birthday: "09-24", dept: "LoveLive!·蓮ノ空女学院スクールアイドルクラブ" },
  { name: "百生吟子", birthday: "10-20", dept: "LoveLive!·蓮ノ空女学院スクールアイドルクラブ" },
  { name: "夕雾缀理", birthday: "11-17", dept: "LoveLive!·蓮ノ空女学院スクールアイドルクラブ" },
  { name: "桂城泉", birthday: "12-01", dept: "LoveLive!·蓮ノ空女学院スクールアイドルクラブ" },
  { name: "藤岛慈", birthday: "12-20", dept: "LoveLive!·蓮ノ空女学院スクールアイドルクラブ" },

  { name: "叶山风花", birthday: "01-28", dept: "声优-徒町小铃" },
  { name: "佐佐木琴子", birthday: "1998-08-28", dept: "声优-夕雾缀理" },
  { name: "花宫初奈", birthday: "1999-10-24", dept: "声优-乙宗梢" },
  { name: "樱井阳菜", birthday: "2000-09-17", dept: "声优-百生吟子" },
  { name: "来栖凛", birthday: "2000-11-08", dept: "声优-安养寺姬芽" },
  { name: "榆井希实", birthday: "2001-05-21", dept: "声优-日野下花帆" },
  { name: "菅叶和", birthday: "2001-11-19", dept: "声优-大泽瑠璃乃" },
  { name: "三宅美羽", birthday: "2001-12-14", dept: "声优-塞拉斯·柳田·利林费尔德" },
  { name: "月音瑚奈", birthday: "2003-08-20", dept: "声优-藤岛慈" },
  { name: "野中心菜", birthday: "2006-01-28", dept: "声优-村野沙耶香" },

  { name: "此花辉夜", birthday: "01-03", dept: "LoveLive!·いきづらい部！" },
  { name: "麻布麻衣", birthday: "02-13", dept: "LoveLive!·いきづらい部！" },
  { name: "金泽奇迹", birthday: "03-02", dept: "LoveLive!·いきづらい部！" },
  { name: "调布乃理子", birthday: "04-04", dept: "LoveLive!·いきづらい部！" },
  { name: "山田真绿", birthday: "05-07", dept: "LoveLive!·いきづらい部！" },
  { name: "驹形花火", birthday: "06-11", dept: "LoveLive!·いきづらい部！" },
  { name: "五桐玲", birthday: "07-09", dept: "LoveLive!·いきづらい部！" },
  { name: "高桥波尔卡", birthday: "08-18", dept: "LoveLive!·いきづらい部！" },
  { name: "春宫悠可里", birthday: "09-22", dept: "LoveLive!·いきづらい部！" },
  { name: "佐佐木翔音", birthday: "11-11", dept: "LoveLive!·いきづらい部！" },

  { name: "小户森穗花", birthday: "01-23", dept: "声优-山田真绿" },
  { name: "藤野心", birthday: "03-31", dept: "声优-驹形花火" },
  { name: "凉之濑葵音", birthday: "06-18", dept: "声优-佐佐木翔音" },
  { name: "濑古梨爱", birthday: "09-19", dept: "声优-调布乃理子" },
  { name: "奥村优季", birthday: "10-13", dept: "声优-春宫悠可里" },
  { name: "绫咲穗音", birthday: "12-31", dept: "声优-高桥波尔卡" },
  { name: "天泽朱音", birthday: "2003-01-19", dept: "声优-此花辉夜" },
  { name: "坂野爱羽", birthday: "2003-05-31", dept: "声优-金泽奇迹" },
  { name: "远藤璃菜", birthday: "2005-10-04", dept: "声优-麻布麻衣" },
  { name: "宫野芹", birthday: "2007-01-05", dept: "声优-五桐玲" },

//少女歌剧
  { name: "石动双叶", birthday: "2001-04-17", dept: "少女歌剧" },
  { name: "露崎真昼", birthday: "2001-05-04", dept: "少女歌剧" },
  { name: "大场奈奈", birthday: "2001-07-12", dept: "少女歌剧" },
  { name: "天堂真矢", birthday: "2001-07-24", dept: "少女歌剧" },
  { name: "西条克洛迪娜", birthday: "2001-08-01", dept: "少女歌剧" },
  { name: "爱城华恋", birthday: "2001-09-27", dept: "少女歌剧" },
  { name: "星见纯那", birthday: "2001-10-01", dept: "少女歌剧" },
  { name: "神乐光", birthday: "2002-01-08", dept: "少女歌剧" },
  { name: "花柳香子", birthday: "2002-03-03", dept: "少女歌剧" },

  { name: "三森铃子", birthday: "1986-06-28", dept: "声优-园田海未、神乐光" },
  { name: "富田麻帆", birthday: "1987-06-01", dept: "声优-天堂真矢" },
  { name: "相羽爱奈", birthday: "1988-10-17", dept: "声优-凑友希那、西条克洛迪娜" },
  { name: "生田辉", birthday: "1991-04-30", dept: "声优-石动双叶" },
  { name: "岩田阳葵", birthday: "1995-04-03", dept: "声优-露崎真昼" },
  { name: "小山百代", birthday: "1995-11-30", dept: "声优-爱城华恋" },
  { name: "小泉萌香", birthday: "1996-02-27", dept: "声优-三船栞子、大场奈奈" },
  { name: "伊藤彩沙", birthday: "1996-08-17", dept: "声优-市谷有咲、花柳香子" },
  { name: "佐藤日向", birthday: "1998-12-23", dept: "声优-星见纯那、晓山瑞希" },

//轻音少女
  { name: "秋山澪", birthday: "01-15", dept: "轻音少女" },
  { name: "琴吹䌷", birthday: "07-02", dept: "轻音少女" },
  { name: "田井中律", birthday: "08-21", dept: "轻音少女" },
  { name: "中野梓", birthday: "11-11", dept: "轻音少女" },
  { name: "平泽唯", birthday: "11-27", dept: "轻音少女" },

  { name: "日笠阳子", birthday: "1985-07-16", dept: "声优-秋山澪、宇田川巴" },
  { name: "佐藤聪美", birthday: "1986-05-08", dept: "声优-琴吹䌷" },
  { name: "丰崎爱生", birthday: "1986-10-28", dept: "声优-平泽唯" },
  { name: "竹达彩奈", birthday: "1989-06-23", dept: "声优-中野梓" },
  { name: "寿美菜子", birthday: "1991-09-17", dept: "声优-琴吹䌷" },

//gbc
  { name: "海老冢智", birthday: "03-22", dept: "Girls Band Cry·TOGENASHI TOGEARI" },
  { name: "安和昴", birthday: "04-27", dept: "Girls Band Cry·TOGENASHI TOGEARI" },
  { name: "RUPA", birthday: "06-28", dept: "Girls Band Cry·TOGENASHI TOGEARI" },
  { name: "井芹仁菜", birthday: "10-24", dept: "Girls Band Cry·TOGENASHI TOGEARI" },
  { name: "河原木桃香", birthday: "12-09", dept: "Girls Band Cry·TOGENASHI TOGEARI" },
  
  { name: "夕莉", birthday: "2000-09-26", dept: "声优-河原木桃香" },
  { name: "凪都", birthday: "2001-08-23", dept: "声优-海老冢智" },
  { name: "美怜", birthday: "2003-11-07", dept: "声优-安和昴" },
  { name: "朱李", birthday: "2003-12-22", dept: "声优-RUPA" },
  { name: "理名", birthday: "2007-11-13", dept: "声优-井芹仁菜" },

//pjsk

  { name: "日野森志步", birthday: "01-08", dept: "Project Sekai·Leo/need" },
  { name: "天马咲希", birthday: "05-09", dept: "Project Sekai·Leo/need" },
  { name: "星乃一歌", birthday: "08-11", dept: "Project Sekai·Leo/need" },
  { name: "望月穗波", birthday: "10-27", dept: "Project Sekai·Leo/need" },

  { name: "桃井爱莉", birthday: "03-19", dept: "Project Sekai·MORE MORE JUMP!" },
  { name: "花里实乃理", birthday: "04-14", dept: "Project Sekai·MORE MORE JUMP!" },
  { name: "桐谷遥", birthday: "10-05", dept: "Project Sekai·MORE MORE JUMP!" },
  { name: "日野森雫", birthday: "12-06", dept: "Project Sekai·MORE MORE JUMP!" },

  { name: "小豆泽心羽", birthday: "03-02", dept: "Project Sekai·Vivid BAD SQUAD" },
  { name: "白石杏", birthday: "07-26", dept: "Project Sekai·Vivid BAD SQUAD" },

  { name: "草薙宁宁", birthday: "07-20", dept: "Project Sekai·Wonderlands×Showtime" },
  { name: "凤笑梦", birthday: "09-09", dept: "Project Sekai·Wonderlands×Showtime" },

  { name: "朝比奈真冬", birthday: "01-27", dept: "Project Sekai·25時、ナイトコードで。" },
  { name: "宵崎奏", birthday: "02-10", dept: "Project Sekai·25時、ナイトコードで。" },
  { name: "东云绘名", birthday: "04-30", dept: "Project Sekai·25時、ナイトコードで。" },
  { name: "晓山瑞希", birthday: "08-27", dept: "Project Sekai·25時、ナイトコードで。" },

  { name: "初音未来", birthday: "08-31", dept: "VOCALOID" },
];